language: cpp

compiler:
  - clang

cache: apt

os:
  - linux
  - osx

notifications:
  irc: "chat.freenode.net#qgis"
  on_failure: change
  on_success: change

before_install:
  - tests/scripts/travis/setup.sh

install:
  - tests/scripts/travis/install.sh

script:
  - tests/scripts/travis/run_tests.sh

