language: cpp

compiler:
  - clang

cache:
  apt: true

os:
  - linux
  - osx

before_install:
  - tests/scripts/travis/setup.sh

install:
  - tests/scripts/travis/configure.sh

script:
  - tests/scripts/travis/build.sh

